name: "bike_share_project"
version: "1.0.0"
config-version: 2

profile: "bike_share_snowflake"

model-paths: ["models"]

models:
  bike_share_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
